spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barbearia?useTimezone=true?serverTimezone=UTC
    username: root
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

api:
  security:
    token:
      secret=${JWT_SECRET:my-secret-key}